---
title: Maak een GameObject van een model
hero_image: images/banner.png
description: Maak een GameObject van een model
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Maak een GameObject van een model
